### ISSUE TITLE
Links fail if .url files lack browser association

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#22]
It seems older chrome versions did not set this properly, or it can be just missing.

Also occurs when trying to accept invites as we try to open discord link which fails.
Setting missing registry entries in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\Shell\Associations\UrlAssociations` should fix this, eg:

https://cdn.discordapp.com/attachments/194127262793203712/480079853987823638/urlAssociations_Chrome.reg
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by Teteros** [comment]
Might be a bit much, a better way would be to find out if we can bring up the dialog in windows (classic control panel for windows 7, "modern" applet for 8/10) where you can set your default browser association for https.

IMO, we should just move the info message _about asking for invites in #contravpn channel_ to launcher first start or first time you open vpnoptions floating window rather than when you click Invite button itself.

This way Invite process will not be blocked by this issue,  which is the bigger problem for new users.

**Comment by Teteros** [comment]
Uses explorer.exe and fallbacks to IE now (76e5419)
