### ISSUE TITLE
Timeout for tinc join

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#23]
Firewalls can leave tinc try to connect to node which generated the invite for a long time.

Maybe we should consider having `tinc join` on a timer which terminates tinc if it failed to join invite in a min or so.
Currently launcher just freezes entirely if this happens (tinc is stuck on `Connecting to [...]` in background)
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by Teteros** [comment]
![ss](https://user-images.githubusercontent.com/5067989/50574997-916fa700-0deb-11e9-8767-0f54030e8409.png)

Freezes on this in console.

**Comment by Teteros** [comment]
> Do I just forbid tinc in firewall?
I would assume so (as a cause of why this is happening in the first place)

You can simply change the existing rules in firewall from `allow` to forbit on tinc/tincd.

**Comment by Teteros** [comment]
Can be re-opened if still persists.

**Comment by ThePredatorBG** [comment]
Reopening since people are still reporting this issue.

**Comment by Teteros** [comment]
I can't think of solutions for this one other than automating the manual method of creating a tinc public/private keypair either via launcher or a bundled script :c

Sending the created public key to the server afterwards is also needed and so it getting the servers public key (`contravpn`) into the clients `hosts`.

This happens rare enough that maybe automating the most troublesome part will do till the cause is found.

**Comment by Teteros** [comment]
ZT implemented
