### ISSUE TITLE
Config folder isn't created on wine

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#30]
Low prio thing since you can create it yourself.

```
Unhandled Exception:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\users\tete\Local Settings\Application Data\Contra'.
  at System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) [0x000f7] in <9727e7c25d434f57880423f7c033fc46>:0
[...]
```
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by Teteros** [comment]
When starting launcher (before the UI even shows up)

This line is causing it https://github.com/ThePredatorBG/contra-launcher/blob/master/Form1.cs#L1795-L1797
It's because `directoryCount` tries to get path of `Contra` folder in `LocalApplicationData` that does not exists at all.

A workaround I just tested quickly was to move the folder creation line:

```cs
//Create vpnconfig folder.
Directory.CreateDirectory(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + @"\Contra\vpnconfig");
```

before it, but that will of course mess up the check for old folder.

The check should be in a try/catch where you create the folder if getting path fails.

**Comment by ThePredatorBG** [comment]
I moved `vpnconfig` folder creation before `directoryCount` and made the check look for 2 or less folders (`<=2`). Message works, so I guess the error is fixed too?

**Comment by Teteros** [comment]
You can push changes to master and I can test for you.
